# -*- coding: utf-8 -*-
"""Customer_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8sqre_lqNSxueCmCJR1i3RJp-FLBVYx
"""

# Step 1 — Import all libraries

# Data handling
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA

# Clustering algorithms
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.mixture import GaussianMixture

# Evaluation metrics
from sklearn.metrics import silhouette_score, silhouette_samples

# Hierarchical clustering
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.spatial.distance import cdist

# Gap statistic
from sklearn.cluster import KMeans as KM
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/Untitled form (Responses) - Form responses 1.csv')
print("Dataset loaded successfully!")
print("\n📊 Shape of dataset:", df.shape)
print("\n📋 Column names:")
for col in df.columns:
    print(" -", col)

print("\n🔍 First 5 rows:")
df.head()

# Check missing values
print("Missing values per column:")
print(df.isnull().sum())

print("\nData types:")
print(df.dtypes)

print("\nBasic statistics:")
df.describe()

# Check unique values for each column
print("Unique values per column:\n")
for col in df.columns:
    print(f"{col}:")
    print(df[col].value_counts())
    print()

"""Data Cleaning"""

# Step 3 — Data Cleaning

# Drop unnecessary columns
df = df.drop(columns=['Timestamp', 'Email address', 'Score'])
print("✅ Dropped unnecessary columns")
print("New shape:", df.shape)

# Rename columns to shorter names for easier handling
df.columns = [
    'age_group',
    'gender',
    'monthly_income',
    'purchase_frequency',
    'spend_per_purchase',
    'shopping_location',
    'online_platforms',
    'purchase_planning',
    'sale_purchase_frequency',
    'sustainable_preference',
    'purchase_influence',
    'brand_loyalty',
    'return_frequency',
    'brand_discovery',
    'delivery_importance',
    'influencer_following',
    'social_media_purchase_likelihood'
]

print("\n Columns renamed successfully!")
print(df.columns.tolist())

# Remove Under 18 responses (not target audience)
print("Before removing under 18:", len(df))
df = df[df['age_group'] != 'Under 18']
print("After removing under 18:", len(df))

# Fix shopping location — keep only single answers
df['shopping_location'] = df['shopping_location'].apply(
    lambda x: x if x in ['Online only', 'In-store only', 'Both equally'] else 'Both equally'
)

# Fix online platforms — replace 'Option 1' with 'Other'
df['online_platforms'] = df['online_platforms'].str.replace('Option 1', 'Other')

# Check missing values
print("\nMissing values after cleaning:")
print(df.isnull().sum())

print("\n Data cleaning complete!")
print("Final shape:", df.shape)

# Fix the 7 missing values — fill with most common answer (mode)
df['sale_purchase_frequency'] = df['sale_purchase_frequency'].fillna(
    df['sale_purchase_frequency'].mode()[0]
)
df['delivery_importance'] = df['delivery_importance'].fillna(
    df['delivery_importance'].mode()[0]
)

# Confirm no missing values remain
print("Missing values after fixing:")
print(df.isnull().sum().sum(), "missing values remaining")
print("\n All missing values handled!")
print("Final shape:", df.shape)

# Quick EDA — plot distribution of key columns
fig, axes = plt.subplots(3, 3, figsize=(15, 12))
fig.suptitle('Fashion Consumer Survey — Key Variable Distributions',
             fontsize=14, fontweight='bold')

cols = ['age_group', 'gender', 'monthly_income',
        'purchase_frequency', 'spend_per_purchase',
        'shopping_location', 'brand_loyalty',
        'sustainable_preference', 'influencer_following']

for i, col in enumerate(cols):
    ax = axes[i//3][i%3]
    df[col].value_counts().plot(kind='bar', ax=ax, color='steelblue')
    ax.set_title(col.replace('_', ' ').title(), fontsize=10)
    ax.set_xlabel('')
    ax.tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig('eda_distributions.png', dpi=150, bbox_inches='tight')
plt.show()
print(" EDA visualisation saved!")

"""Encoding"""

# Step 4 — Encode all categorical variables

from sklearn.preprocessing import LabelEncoder

# Define ordinal mappings for ordered categories
ordinal_mappings = {
    'age_group': ['18-24', '25-34', '35-44', '45+'],
    'monthly_income': ['Under £500', '£500-£1000', '£1000-£2000', '£2000-£3500', '£3500+'],
    'purchase_frequency': ['Rarely', 'Twice a year', 'Every 2-3 months', 'Monthly', 'Weekly'],
    'spend_per_purchase': ['Under £20', '£20-£50', '£50-£100', '£100-£200', '£200+'],
    'purchase_planning': ['I don\'t plan', 'Day before', 'Weeks before', 'Months before'],
    'sale_purchase_frequency': ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'],
    'sustainable_preference': ['Don\'t consider', 'Neutral', 'Somewhat prefer', 'Strongly prefer'],
    'brand_loyalty': ['Not important', 'Neutral', 'Important', 'Very important'],
    'return_frequency': ['Never', 'Rarely', 'Sometimes', 'Very often'],
    'delivery_importance': ['Not important', 'Neutral', 'Important', 'Very important'],
    'influencer_following': ['No', 'Yes, occasionally', 'Yes, regularly'],
    'social_media_purchase_likelihood': ['Very unlikely', 'Unlikely', 'Neutral', 'Likely', 'Very likely'],
}

# Apply ordinal encoding
df_encoded = df.copy()
for col, order in ordinal_mappings.items():
    df_encoded[col] = df_encoded[col].map({val: i for i, val in enumerate(order)})

# Label encode remaining nominal columns
le = LabelEncoder()
nominal_cols = ['gender', 'shopping_location', 'online_platforms',
                'purchase_influence', 'brand_discovery']
for col in nominal_cols:
    df_encoded[col] = le.fit_transform(df_encoded[col])

print(" Encoding complete!")
print("\nSample encoded data:")
print(df_encoded.head())
print("\nAny nulls after encoding:", df_encoded.isnull().sum().sum())

"""Feature Scaling"""

from sklearn.preprocessing import StandardScaler

# Apply StandardScaler
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_encoded)

# Convert back to DataFrame
df_scaled = pd.DataFrame(df_scaled, columns=df_encoded.columns)

print(" Scaling complete!")
print("\nSample scaled data:")
print(df_scaled.head())
print("\nMean of each column (should be close to 0):")
print(df_scaled.mean().round(2))
print("\nStd of each column (should be close to 1):")
print(df_scaled.std().round(2))

"""PCA (Dimensionality Reduction)"""

# Step 6 — PCA

from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt

# First run PCA with all components to see explained variance
pca_full = PCA()
pca_full.fit(df_scaled)

# Calculate cumulative explained variance
cumulative_variance = np.cumsum(pca_full.explained_variance_ratio_) * 100

# Plot explained variance
plt.figure(figsize=(10, 5))
plt.plot(range(1, len(cumulative_variance)+1),
         cumulative_variance, marker='o', color='steelblue', linewidth=2)
plt.axhline(y=80, color='red', linestyle='--', label='80% threshold')
plt.xlabel('Number of Components')
plt.ylabel('Cumulative Explained Variance (%)')
plt.title('PCA — Cumulative Explained Variance')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('pca_variance.png', dpi=150, bbox_inches='tight')
plt.show()

# Find how many components explain 80% variance
n_components = np.argmax(cumulative_variance >= 80) + 1
print(f" Components needed to explain 80% variance: {n_components}")
print(f"Cumulative variance at each component:")
for i, var in enumerate(cumulative_variance):
    print(f"  PC{i+1}: {var:.2f}%")

# Apply PCA with optimal number of components
pca = PCA(n_components=n_components)
df_pca = pca.fit_transform(df_scaled)

print(f" PCA applied successfully!")
print(f"Original shape: {df_scaled.shape}")
print(f"Reduced shape: {df_pca.shape}")
print(f"Total variance explained: {sum(pca.explained_variance_ratio_)*100:.2f}%")

# Also create 2D version for visualisation
pca_2d = PCA(n_components=2)
df_pca_2d = pca_2d.fit_transform(df_scaled)
print(f"\n 2D PCA created for visualisation")
print(f"2D variance explained: {sum(pca_2d.explained_variance_ratio_)*100:.2f}%")

"""K-Means Clustering"""

# Step 7 — K-Means Clustering
# Part A — Elbow Method

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []
K_range = range(2, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(df_pca)
    inertia.append(kmeans.inertia_)

# Plot Elbow Method
plt.figure(figsize=(10, 5))
plt.plot(K_range, inertia, marker='o', color='steelblue', linewidth=2)
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('K-Means — Elbow Method')
plt.grid(True, alpha=0.3)
plt.xticks(K_range)
plt.savefig('kmeans_elbow.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Elbow Method plot done!")

# Part B — Silhouette Scores

from sklearn.metrics import silhouette_score

silhouette_scores = []

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(df_pca)
    score = silhouette_score(df_pca, labels)
    silhouette_scores.append(score)
    print(f"K={k} → Silhouette Score: {score:.4f}")

# Plot Silhouette Scores
plt.figure(figsize=(10, 5))
plt.plot(K_range, silhouette_scores, marker='o',
         color='green', linewidth=2)
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Silhouette Score')
plt.title('K-Means — Silhouette Scores')
plt.grid(True, alpha=0.3)
plt.xticks(K_range)
plt.savefig('kmeans_silhouette.png', dpi=150, bbox_inches='tight')
plt.show()
print(f"\n Best K by Silhouette Score: {K_range[silhouette_scores.index(max(silhouette_scores))]}")

"""Gap Statistic"""

# Part C — Gap Statistic

def compute_gap_statistic(data, k_max=10, n_refs=10, random_state=42):
    gaps = []
    stds = []

    for k in range(2, k_max+1):
        # Fit KMeans on actual data
        kmeans = KMeans(n_clusters=k, random_state=random_state, n_init=10)
        kmeans.fit(data)
        actual_inertia = np.log(kmeans.inertia_)

        # Fit KMeans on random reference datasets
        ref_inertias = []
        for _ in range(n_refs):
            random_data = np.random.uniform(
                low=data.min(axis=0),
                high=data.max(axis=0),
                size=data.shape
            )
            kmeans_ref = KMeans(n_clusters=k, random_state=random_state, n_init=10)
            kmeans_ref.fit(random_data)
            ref_inertias.append(np.log(kmeans_ref.inertia_))

        gap = np.mean(ref_inertias) - actual_inertia
        std = np.std(ref_inertias)
        gaps.append(gap)
        stds.append(std)
        print(f"K={k} → Gap: {gap:.4f}")

    return gaps, stds

print("Running Gap Statistic (takes ~30 seconds)...")
gaps, stds = compute_gap_statistic(df_pca)

# Plot Gap Statistic
plt.figure(figsize=(10, 5))
K_range = range(2, 11)
plt.plot(K_range, gaps, marker='o', color='purple', linewidth=2)
plt.errorbar(K_range, gaps, yerr=stds, fmt='o', color='purple', alpha=0.5)
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Gap Statistic')
plt.title('K-Means — Gap Statistic')
plt.grid(True, alpha=0.3)
plt.xticks(K_range)
plt.savefig('kmeans_gap.png', dpi=150, bbox_inches='tight')
plt.show()

best_k = K_range[np.argmax(gaps)]
print(f"\n Best K by Gap Statistic: {best_k}")

"""K-Means with K=3:"""

# Part D — Final K-Means with K=3

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Final K-Means model
optimal_k = 3
kmeans_final = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
kmeans_labels = kmeans_final.fit_predict(df_pca)

# Add cluster labels to original dataframe
df_encoded['kmeans_cluster'] = kmeans_labels
df['kmeans_cluster'] = kmeans_labels

print(f" K-Means completed with K={optimal_k}")
print(f"\nCluster distribution:")
print(pd.Series(kmeans_labels).value_counts().sort_index())

# Visualise clusters in 2D using PCA
plt.figure(figsize=(10, 6))
colors = ['steelblue', 'coral', 'green']
for i in range(optimal_k):
    mask = kmeans_labels == i
    plt.scatter(df_pca_2d[mask, 0], df_pca_2d[mask, 1],
                c=colors[i], label=f'Cluster {i+1}',
                alpha=0.6, s=60)

plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('K-Means Clustering — 2D PCA Visualisation (K=3)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('kmeans_clusters.png', dpi=150, bbox_inches='tight')
plt.show()

# Final silhouette score
final_score = silhouette_score(df_pca, kmeans_labels)
print(f"\n  Final Silhouette Score (K=3): {final_score:.4f}")

"""DBSCAN Clustering"""

from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
import numpy as np

# Part A — Find best epsilon using k-distance graph
from sklearn.neighbors import NearestNeighbors

neighbors = NearestNeighbors(n_neighbors=5)
neighbors.fit(df_pca)
distances, indices = neighbors.kneighbors(df_pca)
distances = np.sort(distances[:, 4], axis=0)

plt.figure(figsize=(10, 5))
plt.plot(distances, color='steelblue', linewidth=2)
plt.xlabel('Data Points sorted by distance')
plt.ylabel('5th Nearest Neighbour Distance')
plt.title('DBSCAN — K-Distance Graph (to find optimal epsilon)')
plt.grid(True, alpha=0.3)
plt.savefig('dbscan_kdistance.png', dpi=150, bbox_inches='tight')
plt.show()
print(" K-Distance graph done!")
print("Look for the 'elbow' point in the graph — that's your epsilon value")

# Part B — Run DBSCAN with different epsilon values

results = []
epsilons = [0.5, 0.8, 1.0, 1.2, 1.5, 2.0, 2.5, 3.0]

for eps in epsilons:
    dbscan = DBSCAN(eps=eps, min_samples=5)
    labels = dbscan.fit_predict(df_pca)

    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    n_noise = list(labels).count(-1)

    if n_clusters >= 2:
        score = silhouette_score(df_pca, labels)
    else:
        score = -1

    results.append({
        'epsilon': eps,
        'n_clusters': n_clusters,
        'n_noise': n_noise,
        'silhouette': round(score, 4)
    })
    print(f"eps={eps} → Clusters: {n_clusters}, Noise: {n_noise}, Silhouette: {score:.4f}")

results_df = pd.DataFrame(results)
print("\n DBSCAN parameter search complete!")
print(results_df)

# Part C — Final DBSCAN with best parameters

# Choose best epsilon (most clusters with least noise)
best_eps = 1.5  # We will adjust based on results above

dbscan_final = DBSCAN(eps=best_eps, min_samples=5)
dbscan_labels = dbscan_final.fit_predict(df_pca)

n_clusters = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
n_noise = list(dbscan_labels).count(-1)

print(f" Final DBSCAN Results:")
print(f"Epsilon: {best_eps}")
print(f"Number of clusters: {n_clusters}")
print(f"Number of noise points: {n_noise}")

# Visualise DBSCAN clusters
plt.figure(figsize=(10, 6))
unique_labels = set(dbscan_labels)
colors = plt.cm.tab10(np.linspace(0, 1, len(unique_labels)))

for label, color in zip(unique_labels, colors):
    if label == -1:
        color = 'black'
        marker = 'x'
        label_name = 'Noise'
    else:
        marker = 'o'
        label_name = f'Cluster {label + 1}'

    mask = dbscan_labels == label
    plt.scatter(df_pca_2d[mask, 0], df_pca_2d[mask, 1],
                c=[color], label=label_name,
                alpha=0.6, s=60, marker=marker)

plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title(f'DBSCAN Clustering — 2D PCA Visualisation (eps={best_eps})')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('dbscan_clusters.png', dpi=150, bbox_inches='tight')
plt.show()

if n_clusters >= 2:
    valid_mask = dbscan_labels != -1
    dbscan_score = silhouette_score(df_pca[valid_mask], dbscan_labels[valid_mask])
    print(f"\n DBSCAN Silhouette Score: {dbscan_score:.4f}")

df['dbscan_cluster'] = dbscan_labels
print(" DBSCAN labels added to dataframe!")

# Document DBSCAN result

print("=" * 50)
print("DBSCAN FINDINGS SUMMARY")
print("=" * 50)
print("DBSCAN did not produce meaningful clusters")
print("for this survey dataset.")
print("Reason: Survey data lacks density-based")
print("cluster structure required by DBSCAN.")
print("Best epsilon tried: 2.0")
print("Clusters found: 4 (but 330/362 = 91% noise)")
print("Conclusion: DBSCAN not suitable for this data")
print("This is a valid and documented finding.")
print("=" * 50)

# Save best available DBSCAN result for comparison
dbscan_best = DBSCAN(eps=2.0, min_samples=5)
dbscan_labels = dbscan_best.fit_predict(df_pca)
df['dbscan_cluster'] = dbscan_labels

print("\n DBSCAN result documented and saved!")

"""Hierarchical Clustering"""

# Step 9 — Hierarchical Clustering
# Part A — Dendrogram

from scipy.cluster.hierarchy import dendrogram, linkage
import matplotlib.pyplot as plt

# Generate linkage matrix
linked = linkage(df_pca, method='ward')

# Plot Dendrogram
plt.figure(figsize=(12, 6))
dendrogram(linked,
           truncate_mode='lastp',
           p=30,
           leaf_rotation=45,
           leaf_font_size=10,
           show_contracted=True)
plt.title('Hierarchical Clustering — Dendrogram (Ward Linkage)')
plt.xlabel('Sample Index or Cluster Size')
plt.ylabel('Distance')
plt.grid(True, alpha=0.3)
plt.savefig('hierarchical_dendrogram.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Dendrogram plotted!")
print("Look for the largest vertical gap — that suggests optimal clusters")

# Part B — Try different linkage methods

from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

linkage_methods = ['ward', 'complete', 'average', 'single']
n_clusters = 3

print("Comparing linkage methods with K=3:\n")
best_score = -1
best_method = ''

for method in linkage_methods:
    hc = AgglomerativeClustering(n_clusters=n_clusters, linkage=method)
    labels = hc.fit_predict(df_pca)
    score = silhouette_score(df_pca, labels)
    print(f"Linkage: {method:10s} → Silhouette Score: {score:.4f}")

    if score > best_score:
        best_score = score
        best_method = method

print(f"\n Best linkage method: {best_method}")
print(f" Best silhouette score: {best_score:.4f}")

# Part C — Final Hierarchical Clustering with best linkage

hc_final = AgglomerativeClustering(n_clusters=3, linkage=best_method)
hc_labels = hc_final.fit_predict(df_pca)

print(f" Hierarchical Clustering completed!")
print(f"Linkage method: {best_method}")
print(f"\nCluster distribution:")
print(pd.Series(hc_labels).value_counts().sort_index())

# Visualise
plt.figure(figsize=(10, 6))
colors = ['steelblue', 'coral', 'green']
for i in range(3):
    mask = hc_labels == i
    plt.scatter(df_pca_2d[mask, 0], df_pca_2d[mask, 1],
                c=colors[i], label=f'Cluster {i+1}',
                alpha=0.6, s=60)

plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title(f'Hierarchical Clustering — 2D PCA Visualisation ({best_method} linkage)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('hierarchical_clusters.png', dpi=150, bbox_inches='tight')
plt.show()

hc_score = silhouette_score(df_pca, hc_labels)
print(f"\n Final Silhouette Score: {hc_score:.4f}")
df['hierarchical_cluster'] = hc_labels
print(" Hierarchical labels added to dataframe!")

# Fix Hierarchical Clustering — use Ward linkage instead of single

hc_final = AgglomerativeClustering(n_clusters=3, linkage='ward')
hc_labels = hc_final.fit_predict(df_pca)

print("✅ Hierarchical Clustering with Ward linkage:")
print(f"\nCluster distribution:")
print(pd.Series(hc_labels).value_counts().sort_index())

# Visualise
plt.figure(figsize=(10, 6))
colors = ['steelblue', 'coral', 'green']
for i in range(3):
    mask = hc_labels == i
    plt.scatter(df_pca_2d[mask, 0], df_pca_2d[mask, 1],
                c=colors[i], label=f'Cluster {i+1}',
                alpha=0.6, s=60)

plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('Hierarchical Clustering — 2D PCA Visualisation (Ward linkage)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('hierarchical_clusters.png', dpi=150, bbox_inches='tight')
plt.show()

hc_score = silhouette_score(df_pca, hc_labels)
print(f"\n✅ Final Silhouette Score (Ward): {hc_score:.4f}")
df['hierarchical_cluster'] = hc_labels
print("✅ Hierarchical labels saved!")

"""Agglomerative Clustering"""

# Step 10 — Agglomerative Clustering
# Comparing different linkage strategies properly

from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

linkage_methods = ['ward', 'complete', 'average']
results_agg = []

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
colors = ['steelblue', 'coral', 'green']

for idx, method in enumerate(linkage_methods):
    agg = AgglomerativeClustering(n_clusters=3, linkage=method)
    labels = agg.fit_predict(df_pca)
    score = silhouette_score(df_pca, labels)
    dist = pd.Series(labels).value_counts().sort_index().tolist()

    results_agg.append({
        'linkage': method,
        'silhouette': round(score, 4),
        'cluster_sizes': dist
    })

    # Plot each linkage
    for i in range(3):
        mask = labels == i
        axes[idx].scatter(df_pca_2d[mask, 0], df_pca_2d[mask, 1],
                         c=colors[i], label=f'Cluster {i+1}',
                         alpha=0.6, s=40)
    axes[idx].set_title(f'Agglomerative — {method}\nSilhouette: {score:.4f}')
    axes[idx].set_xlabel('PC1')
    axes[idx].set_ylabel('PC2')
    axes[idx].legend()
    axes[idx].grid(True, alpha=0.3)

    print(f"Linkage: {method:10s} → Silhouette: {score:.4f} | Clusters: {dist}")

plt.suptitle('Agglomerative Clustering — Linkage Comparison',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('agglomerative_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n Agglomerative comparison complete!")

# Final Agglomerative with best linkage (Ward — most balanced)

agg_final = AgglomerativeClustering(n_clusters=3, linkage='ward')
agg_labels = agg_final.fit_predict(df_pca)

print(" Final Agglomerative Clustering (Ward):")
print(f"\nCluster distribution:")
print(pd.Series(agg_labels).value_counts().sort_index())

agg_score = silhouette_score(df_pca, agg_labels)
print(f"\n Final Silhouette Score: {agg_score:.4f}")

df['agglomerative_cluster'] = agg_labels
print(" Agglomerative labels saved!")

"""Gaussian Mixture Models (GMM)"""

# Step 11 — Gaussian Mixture Models (GMM)
# Part A — Find optimal components using BIC and AIC

from sklearn.mixture import GaussianMixture
import matplotlib.pyplot as plt

bic_scores = []
aic_scores = []
n_components_range = range(2, 11)

for n in n_components_range:
    gmm = GaussianMixture(n_components=n, random_state=42, n_init=5)
    gmm.fit(df_pca)
    bic_scores.append(gmm.bic(df_pca))
    aic_scores.append(gmm.aic(df_pca))
    print(f"Components: {n} → BIC: {gmm.bic(df_pca):.2f} | AIC: {gmm.aic(df_pca):.2f}")

# Plot BIC and AIC
plt.figure(figsize=(10, 5))
plt.plot(n_components_range, bic_scores, marker='o',
         color='steelblue', linewidth=2, label='BIC')
plt.plot(n_components_range, aic_scores, marker='s',
         color='coral', linewidth=2, label='AIC')
plt.xlabel('Number of Components')
plt.ylabel('Score')
plt.title('GMM — BIC and AIC Scores (lower is better)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.xticks(n_components_range)
plt.savefig('gmm_bic_aic.png', dpi=150, bbox_inches='tight')
plt.show()

best_n_bic = n_components_range[bic_scores.index(min(bic_scores))]
best_n_aic = n_components_range[aic_scores.index(min(aic_scores))]
print(f"\n Best components by BIC: {best_n_bic}")
print(f" Best components by AIC: {best_n_aic}")

# Part B — Final GMM with optimal components

best_n = 3  # We use 3 to stay consistent with other algorithms

gmm_final = GaussianMixture(n_components=best_n,
                             random_state=42, n_init=5)
gmm_final.fit(df_pca)
gmm_labels = gmm_final.predict(df_pca)

print(f" GMM completed with {best_n} components!")
print(f"\nCluster distribution:")
print(pd.Series(gmm_labels).value_counts().sort_index())

# Visualise
plt.figure(figsize=(10, 6))
colors = ['steelblue', 'coral', 'green']
for i in range(best_n):
    mask = gmm_labels == i
    plt.scatter(df_pca_2d[mask, 0], df_pca_2d[mask, 1],
                c=colors[i], label=f'Cluster {i+1}',
                alpha=0.6, s=60)

plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title(f'GMM Clustering — 2D PCA Visualisation ({best_n} components)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('gmm_clusters.png', dpi=150, bbox_inches='tight')
plt.show()

gmm_score = silhouette_score(df_pca, gmm_labels)
print(f"\n GMM Silhouette Score: {gmm_score:.4f}")
df['gmm_cluster'] = gmm_labels
print(" GMM labels saved!")

"""Full Algorithm Comparison"""

# Step 12 — Algorithm Comparison Table

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import silhouette_score

# Collect all results
comparison = {
    'Algorithm': [
        'K-Means',
        'DBSCAN',
        'Hierarchical (Average)',
        'Agglomerative (Ward)',
        'GMM'
    ],
    'Clusters Found': [3, 'N/A (failed)', 3, 3, 3],
    'Silhouette Score': [
        round(silhouette_score(df_pca, kmeans_labels), 4),
        'N/A',
        round(silhouette_score(df_pca, hc_labels), 4),
        round(silhouette_score(df_pca, agg_labels), 4),
        round(silhouette_score(df_pca, gmm_labels), 4)
    ],
    'Suitable for Survey Data': [
        'Yes', 'No', 'Yes', 'Yes', 'Yes'
    ],
    'Notes': [
        'Best overall — clear balanced clusters',
        'Failed — survey data not density-based',
        'Good — average linkage avoided chaining',
        'Good — ward linkage most balanced',
        'Good — soft probabilistic membership'
    ]
}

comparison_df = pd.DataFrame(comparison)
print("=" * 80)
print("CLUSTERING ALGORITHM COMPARISON")
print("=" * 80)
print(comparison_df.to_string(index=False))
print("=" * 80)

# Visualise comparison — Silhouette Scores bar chart

algorithms = ['K-Means', 'Hierarchical\n(Average)',
              'Agglomerative\n(Ward)', 'GMM']
scores = [
    silhouette_score(df_pca, kmeans_labels),
    silhouette_score(df_pca, hc_labels),
    silhouette_score(df_pca, agg_labels),
    silhouette_score(df_pca, gmm_labels)
]
colors_bar = ['steelblue', 'green', 'coral', 'purple']

plt.figure(figsize=(10, 6))
bars = plt.bar(algorithms, scores, color=colors_bar,
               edgecolor='white', width=0.5)

# Add score labels on bars
for bar, score in zip(bars, scores):
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.001,
             f'{score:.4f}', ha='center',
             va='bottom', fontsize=11, fontweight='bold')

plt.xlabel('Clustering Algorithm')
plt.ylabel('Silhouette Score')
plt.title('Algorithm Comparison — Silhouette Scores\n(Higher is better | DBSCAN excluded — not suitable)')
plt.ylim(0, max(scores) + 0.05)
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.savefig('algorithm_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Algorithm comparison complete!")
print(f"\n Best algorithm: K-Means (Score: {max(scores):.4f})")

"""Customer Segment Profiling"""

# Step 13 — Customer Segment Profiling
# Part A — Analyse each cluster characteristics

# Use K-Means labels (best algorithm)
df['final_cluster'] = kmeans_labels

# Get mean values for each cluster
cluster_profiles = df.groupby('final_cluster')[
    ['age_group', 'monthly_income', 'purchase_frequency',
     'spend_per_purchase', 'shopping_location', 'sale_purchase_frequency',
     'sustainable_preference', 'brand_loyalty', 'return_frequency',
     'delivery_importance', 'influencer_following',
     'social_media_purchase_likelihood']
].apply(lambda x: x.mode().iloc[0])

print("=" * 60)
print("CLUSTER PROFILES — Most Common Response Per Cluster")
print("=" * 60)
print(cluster_profiles.T)

# Part B — Cluster size and key stats

print("Cluster Sizes:")
print(df['final_cluster'].value_counts().sort_index())
print()

for cluster in range(3):
    subset = df[df['final_cluster'] == cluster]
    print(f"\n{'='*50}")
    print(f"CLUSTER {cluster+1} — {len(subset)} respondents")
    print(f"{'='*50}")
    print(f"Age group:          {subset['age_group'].mode()[0]}")
    print(f"Monthly income:     {subset['monthly_income'].mode()[0]}")
    print(f"Purchase frequency: {subset['purchase_frequency'].mode()[0]}")
    print(f"Spend per purchase: {subset['spend_per_purchase'].mode()[0]}")
    print(f"Shopping location:  {subset['shopping_location'].mode()[0]}")
    print(f"Brand loyalty:      {subset['brand_loyalty'].mode()[0]}")
    print(f"Sustainability:     {subset['sustainable_preference'].mode()[0]}")
    print(f"Influencer follow:  {subset['influencer_following'].mode()[0]}")
    print(f"Social media buy:   {subset['social_media_purchase_likelihood'].mode()[0]}")

"""Heatmap of cluster profiles"""

# Fix — use encoded dataframe for profiling instead

# Create cluster profiles using encoded (numeric) data
df_encoded['final_cluster'] = kmeans_labels

numeric_cols = ['monthly_income', 'purchase_frequency',
                'spend_per_purchase', 'brand_loyalty',
                'sustainable_preference', 'delivery_importance',
                'influencer_following',
                'social_media_purchase_likelihood',
                'sale_purchase_frequency', 'return_frequency']

# Get mean values per cluster from encoded data
cluster_means = df_encoded.groupby('final_cluster')[numeric_cols].mean()

print(" Cluster means calculated!")
print(cluster_means)

# Fixed Heatmap

import seaborn as sns

cluster_means.index = [
    'Aspiring Fashion\nEnthusiasts',
    'Casual Budget\nShoppers',
    'Conscious Trend\nFollowers'
]

plt.figure(figsize=(12, 5))
sns.heatmap(cluster_means,
            annot=True, fmt='.2f',
            cmap='YlOrRd',
            linewidths=0.5,
            cbar_kws={'label': 'Mean Value'})
plt.title('Customer Segment Profiles — Feature Heatmap',
          fontsize=13, fontweight='bold')
plt.xlabel('Features')
plt.ylabel('Customer Segments')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('segment_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Heatmap saved!")

"""Bar Chart:"""

# Fixed Bar Charts

features = ['monthly_income', 'spend_per_purchase',
            'brand_loyalty', 'sustainable_preference',
            'influencer_following',
            'social_media_purchase_likelihood']

segment_names = ['Aspiring Fashion\nEnthusiasts',
                 'Casual Budget\nShoppers',
                 'Conscious Trend\nFollowers']

fig, axes = plt.subplots(2, 3, figsize=(15, 10))
fig.suptitle('Customer Segment Comparison — Key Features',
             fontsize=14, fontweight='bold')

colors = ['steelblue', 'coral', 'green']

for idx, feature in enumerate(features):
    ax = axes[idx//3][idx%3]
    values = [df_encoded[df_encoded['final_cluster']==i][feature].mean()
              for i in range(3)]
    bars = ax.bar(segment_names, values, color=colors,
                  edgecolor='white')
    ax.set_title(feature.replace('_', ' ').title(), fontsize=10)
    ax.set_ylabel('Mean Value')
    ax.tick_params(axis='x', rotation=15)
    ax.grid(True, alpha=0.3, axis='y')
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 0.01,
                f'{val:.2f}', ha='center',
                va='bottom', fontsize=9)

plt.tight_layout()
plt.savefig('segment_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Bar charts saved!")

"""Rador Chart:"""

from sklearn.preprocessing import MinMaxScaler
import numpy as np

radar_features = ['monthly_income', 'spend_per_purchase',
                  'brand_loyalty', 'sustainable_preference',
                  'influencer_following',
                  'social_media_purchase_likelihood',
                  'sale_purchase_frequency']

radar_data = df_encoded.groupby('final_cluster')[radar_features].mean()
scaler_radar = MinMaxScaler()
radar_normalised = scaler_radar.fit_transform(radar_data)

num_vars = len(radar_features)
angles = np.linspace(0, 2*np.pi, num_vars,
                     endpoint=False).tolist()
angles += angles[:1]

segment_names = ['Aspiring Fashion Enthusiasts',
                 'Casual Budget Shoppers',
                 'Conscious Trend Followers']
colors = ['steelblue', 'coral', 'green']

fig, axes = plt.subplots(1, 3, figsize=(18, 6),
                          subplot_kw=dict(polar=True))
fig.suptitle('Customer Segment Radar Charts',
             fontsize=14, fontweight='bold')

for idx, (ax, name, color) in enumerate(
        zip(axes, segment_names, colors)):
    values = radar_normalised[idx].tolist()
    values += values[:1]

    ax.plot(angles, values, color=color, linewidth=2)
    ax.fill(angles, values, color=color, alpha=0.25)
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels([l.replace('_', '\n')
                        for l in radar_features], size=8)
    ax.set_title(name, size=10, fontweight='bold',
                 pad=15, color=color)
    ax.set_ylim(0, 1)
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('segment_radar.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Radar charts saved!")